version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dalvare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ../.docker-volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    volumes:
      - ../.docker-volumes/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"

  service:
    build: ./
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db
