version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dalvare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ../.docker-volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service:
    build: ./
    environment:
      - DB_URL=mysql://admin:admin@db:3306/dalvare
      - TESTING=False
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db
