version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dalvare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ../.docker-volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"